spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:mytestdb
    username: sa
    password:
  h2:
    console.enabled: true
